config/routes.rb
Rails.application.routes.draw do
  root 'dishes#index'
  resources :courses
  resources :dishes

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :dishes
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # validates :name, presence: true
  # validates :name, uniqueness: true

  # GET /dishes
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      redirect_to @dish, notice: 'Dish was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dishes/1
  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Dish was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /dishes/1
  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: 'Dish was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dish_params
      params.require(:dish).permit(:course_id, :price, :name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.collection_select(:course_id, Course.all, :id, :name, include_blank: true) %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<div class="menu" align= center>
  <h1> :. Big A's Backyard Barbeque! .: </h1>
  <h4> Too delicious to be a legitimate business</h4>
  <h5>123 Fake Address Lane<br>
     Not-A-City NC, 00000</h5>
  <h5>(919)555-5555<h5>
</div>
<br><br>
  <div class="menu-items" align= center>
  <h2>Menu</h2>
  =====================================<br><br>
  <h3>Appetizers</h3>
  <h5>Prepare yourself for the deliciousness that is about to come... BY EATING SOME DELICIOUSNESS!</h5>
  <%= image_tag asset_url("appetizer.jpg"), class: "food-pics"%><br><br>
      <% @dishes.each do |dish| %>
        <% if dish.course_id == 1 %>
          <p>
            <p><span class="dish-info"><%= link_to dish.name, edit_dish_path(dish) %>
              <br>Price: $<%= dish.price %></span></p>
            <p><span class="description"><%= dish.description %></p></span>
            </p>
          <% end %>
        <% end %>
  <br><br>
  -------------------------------------<br>
  <h3>Entrees</h3>
  <h5>Where the REAL party begins. This is what you came here for, right?</h5>
    <%= image_tag asset_url("entree.jpg"), class: "food-pics"%><br><br>
  <% @dishes.each do |dish| %>
    <% if dish.course_id == 2 %>
      <p>
        <p><span class="dish-info"><%= link_to dish.name, edit_dish_path(dish) %> <br>
          Price: $<%= dish.price %></span></p>
        <p><span class="description"><%= dish.description %></p></span>
        </p>
      <% end %>
    <% end %>
<br><br>
  -------------------------------------<br>
  <h3>Desserts!</h3>
  <h5>I know you're not full already! There's gotta be room in there for some more goodies!</h5>
      <%= image_tag asset_url("dessert.jpg"), class: "food-pics"%><br><br>
  <% @dishes.each do |dish| %>
    <% if dish.course_id == 3 %>
      <p>
        <p><span class="dish-info"><%= link_to dish.name, edit_dish_path(dish) %>
          <br>Price: $<%= dish.price %></span></p>
        <p><span class="description"><%= dish.description %></p></span>
        </p>
      <% end %>
    <% end %>
  </div>
<br><br>



  =======================<br>
  <%= link_to "Add A new Item to Menu", new_dish_path %> |
  <br>=======================
  <br>Made by Anthony Ellis.  Here's a link to <a href="https://github.com/hieshin431"> My GitHub!</a>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @dish.course_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>